version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "18000:80"
        volumes:
            - ./Project:/var/www/html #프로젝트 경로
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf #nginx 설정 파일

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password

    php:
        image: php:7.4-fpm
        container_name: php
        volumes:
            - ./Project:/var/www/html #프로젝트 경로
        ports:
            - "9000:9000"
        command:
            - /bin/sh
            - -c
            - |
              echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
              php-fpm
